-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Versión del servidor:         10.4.20-MariaDB - mariadb.org binary distribution
-- SO del servidor:              Win64
-- HeidiSQL Versión:             11.3.0.6295
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Volcando estructura para tabla tareas.failed_jobs
CREATE TABLE IF NOT EXISTS `failed_jobs` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `uuid` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `connection` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `queue` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `payload` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `exception` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `failed_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `failed_jobs_uuid_unique` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla tareas.failed_jobs: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `failed_jobs` DISABLE KEYS */;
/*!40000 ALTER TABLE `failed_jobs` ENABLE KEYS */;

-- Volcando estructura para tabla tareas.migrations
CREATE TABLE IF NOT EXISTS `migrations` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `migration` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `batch` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla tareas.migrations: ~5 rows (aproximadamente)
/*!40000 ALTER TABLE `migrations` DISABLE KEYS */;
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES
	(1, '2014_10_12_000000_create_users_table', 1),
	(2, '2014_10_12_100000_create_password_resets_table', 1),
	(3, '2019_08_19_000000_create_failed_jobs_table', 1),
	(4, '2019_12_14_000001_create_personal_access_tokens_table', 1),
	(5, '2021_12_20_042936_create_tasks_table', 1);
/*!40000 ALTER TABLE `migrations` ENABLE KEYS */;

-- Volcando estructura para tabla tareas.password_resets
CREATE TABLE IF NOT EXISTS `password_resets` (
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  KEY `password_resets_email_index` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla tareas.password_resets: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `password_resets` DISABLE KEYS */;
/*!40000 ALTER TABLE `password_resets` ENABLE KEYS */;

-- Volcando estructura para tabla tareas.personal_access_tokens
CREATE TABLE IF NOT EXISTS `personal_access_tokens` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `tokenable_type` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tokenable_id` bigint(20) unsigned NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `abilities` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `last_used_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `personal_access_tokens_token_unique` (`token`),
  KEY `personal_access_tokens_tokenable_type_tokenable_id_index` (`tokenable_type`,`tokenable_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla tareas.personal_access_tokens: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `personal_access_tokens` DISABLE KEYS */;
/*!40000 ALTER TABLE `personal_access_tokens` ENABLE KEYS */;

-- Volcando estructura para tabla tareas.tasks
CREATE TABLE IF NOT EXISTS `tasks` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) unsigned NOT NULL,
  `task` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `date` date NOT NULL,
  `expiration_date` date NOT NULL,
  `finished` varchar(5) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_tasks_users_idx` (`user_id`),
  CONSTRAINT `fk_tasks_users` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=104 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla tareas.tasks: ~86 rows (aproximadamente)
/*!40000 ALTER TABLE `tasks` DISABLE KEYS */;
INSERT INTO `tasks` (`id`, `user_id`, `task`, `description`, `date`, `expiration_date`, `finished`, `created_at`, `updated_at`) VALUES
	(6, 0, 'Est et labore molestiae aliquam aut autem quis. Vel est et atque provident facere non impedit.', 'Et quia expedita nihil natus reiciendis cum et. Ut dolorem quia quas eos. Neque odit aut libero temporibus est distinctio. Ipsam quisquam blanditiis omnis odio suscipit repellendus. Natus sapiente delectus dolores consectetur. Non non reprehenderit autem voluptate deleniti. Dolore dicta rerum magni. Qui accusantium iusto accusantium sit. Provident error voluptatem veniam aut magni in nam. Aliquam amet quisquam expedita aspernatur nulla non repellat ducimus.', '2021-12-20', '2021-12-20', 'NO', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(7, 0, 'Ipsam hic blanditiis iure officiis voluptatem ut quae. Distinctio laboriosam aut eum. Voluptatem atque qui aut eligendi quis.', 'Voluptatum ratione qui eaque ut. A velit aliquid voluptas. Dolorem et unde quo ipsam ut id. Sapiente quod illum ut et labore eius rerum sed. Ipsam ut culpa corrupti eaque perferendis corrupti. Voluptas eum quidem repudiandae. Accusantium incidunt mollitia numquam quae hic perspiciatis sed. Ratione sunt optio dolorum illum ullam et et consequuntur. Magnam ratione alias at voluptatem placeat voluptatem. Veritatis est officia facere totam soluta.', '2021-12-20', '2021-12-20', 'SI', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(8, 0, 'Soluta aspernatur non incidunt qui dolorum magnam. Aliquam saepe et quia fuga quasi est.', 'Non quia consectetur ad dolorem eos ut dolores. Distinctio ducimus iste accusamus placeat consequatur mollitia. Eligendi enim officia distinctio. Expedita quo pariatur iusto cumque. Officiis ea voluptatem sequi fugit porro est. Reprehenderit voluptas iusto repellat ad. Rerum et et eligendi quo praesentium voluptate. Est cum officia doloribus consequatur libero. Vel labore voluptatem molestiae rerum quo. Autem laborum fugiat maiores commodi sunt consequatur quia.', '2021-12-20', '2021-12-20', 'NO', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(9, 0, 'Odit soluta consequuntur soluta saepe eligendi eum debitis numquam. Quam libero eligendi autem error fugiat nihil numquam. Enim ut non iusto cupiditate minima.', 'Adipisci necessitatibus sapiente voluptate eos qui. Quidem incidunt placeat tempora pariatur qui occaecati. Aut sunt consequuntur laudantium eum eos hic. Eum dolorum modi voluptatem autem omnis rerum. In similique eum autem doloribus doloribus esse et. Accusamus molestiae autem molestiae autem expedita quia eius et. Omnis quasi iure delectus iste perspiciatis et ex. Rem consequatur molestiae nisi cupiditate commodi necessitatibus.', '2021-12-20', '2021-12-20', 'SI', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(10, 0, 'Autem iure est suscipit. Aut iste perferendis aspernatur nisi est. Assumenda consectetur quis quam error provident error corporis.', 'Voluptatem voluptatum natus odit sequi ipsa ratione veritatis molestiae. Et ut quo porro rerum sunt aut facilis. Quod eos debitis non vel. Dolore iste est in expedita nihil debitis tempore. Magnam sequi molestiae quaerat quia. Voluptatem labore itaque quis magni. Ut minima suscipit optio culpa. Temporibus impedit quasi ad debitis. Fugit sunt culpa quia voluptatum.', '2021-12-20', '2021-12-20', 'NO', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(11, 0, 'Exercitationem ratione qui sit ut facilis dolores omnis. Ratione eveniet in voluptatem qui laudantium et unde. Quod ut dolore eum.', 'Magnam mollitia esse velit facere quo. Quod cum dolor eum quo. Voluptatem officiis aut blanditiis beatae enim recusandae. Exercitationem non atque autem inventore. Autem eaque et odit aliquam quisquam dignissimos. Blanditiis explicabo minus praesentium sit vel voluptas sequi consectetur. Perspiciatis aut voluptas nostrum.', '2021-12-20', '2021-12-20', 'SI', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(12, 0, 'In sit rerum quis est atque eligendi. Est ut nemo omnis quibusdam ut hic sunt. In in quasi repudiandae vel at eius.', 'Quaerat cum est laboriosam dignissimos esse quia explicabo. Ex necessitatibus iusto dolorem excepturi saepe. Aut quasi quis quisquam sequi et impedit. Nihil soluta quia et at officia eum nisi. Cumque praesentium veniam quaerat inventore molestiae. Illum reprehenderit in pariatur cupiditate soluta excepturi.', '2021-12-20', '2021-12-20', 'NO', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(13, 0, 'Dolorum et in nesciunt ex sit ipsa reprehenderit. Est consequatur illum esse quas mollitia voluptas. Eveniet expedita eum voluptatem nihil repellendus error.', 'Ipsam voluptas aspernatur quidem fugit veniam dolore. Eos et et accusamus est adipisci facere molestias. Sapiente omnis ducimus quia eum. Voluptatem eos odit fuga perspiciatis molestiae sit. Iusto consectetur aut ut dolore qui. Reiciendis ut temporibus molestias error molestiae. Eius aliquid delectus soluta ut. In aperiam a molestiae. Ipsum ipsa voluptatem magni voluptas quasi aut optio. Doloribus deserunt provident fugit adipisci libero.', '2021-12-20', '2021-12-20', 'NO', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(14, 0, 'Quisquam consequatur et quaerat adipisci sit rerum quia. Voluptatem odit ut sapiente beatae in labore dolore. Non illum dolores harum vitae cum quis sequi.', 'Nihil fugiat adipisci dolores debitis esse alias aspernatur. Ipsam asperiores quos quaerat officia. Dicta dolor dolor qui illum. Iste adipisci ducimus neque velit eveniet. Numquam laudantium animi voluptatem pariatur omnis distinctio. Velit quasi quia aut odio ipsam. Ad sint ea quis nemo doloremque perferendis. Natus consequatur quos omnis saepe culpa beatae consequatur. Voluptatem autem aut quia non error pariatur sequi aut.', '2021-12-20', '2021-12-20', 'NO', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(15, 0, 'Tempora expedita qui quo non quo enim. Commodi possimus rerum aut modi. Modi molestias vero eum. Adipisci enim et quisquam ex reprehenderit.', 'Alias consectetur repudiandae ducimus. Eius omnis modi atque voluptate id voluptatem quasi. Incidunt animi quas sit mollitia. Dolor perspiciatis eius earum aut vero expedita deserunt. Et voluptas aut nostrum illo. Est veniam ipsum repellat eos ut sed molestiae. Aut ut qui illum. Eius cum quis incidunt dolores aut quo. Aliquid minus sapiente ut eum voluptate soluta. Laboriosam enim quia quo exercitationem ducimus ipsam. Aut eius dolores itaque repellendus sit assumenda.', '2021-12-20', '2021-12-20', 'NO', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(16, 0, 'Quia eos repudiandae est adipisci corrupti. Voluptas ducimus esse ab sed aspernatur perspiciatis et dolores. Sunt laudantium iste eum voluptatibus. Ut voluptatem nesciunt et atque iste.', 'Praesentium eos commodi sed aut non fugiat itaque iure. Est repellendus impedit et non. Vel eius velit odio saepe. Sunt ut neque id vitae saepe. Unde dolores modi exercitationem. Quam incidunt omnis veritatis non officia earum et. Sint maxime praesentium ab excepturi animi dignissimos.', '2021-12-20', '2021-12-20', 'NO', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(17, 0, 'Ut sapiente voluptatum autem esse. Ea dolor labore et repellat rerum. Odit qui tempore animi nostrum atque.', 'Ducimus necessitatibus nihil a dolor. Voluptatum aut autem deserunt est. Ut sint eos veniam voluptatibus est. Nisi qui est sit quibusdam quis. Omnis enim sunt doloremque. Provident quia quae porro consectetur optio corrupti. Earum incidunt a enim quasi. Sed similique autem labore quae suscipit. Corrupti reiciendis sint ducimus nisi. Consequatur quis est commodi omnis ipsum minima. Beatae quae cupiditate dolor dignissimos eum sunt corporis.', '2021-12-20', '2021-12-20', 'NO', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(18, 0, 'Nostrum vitae nulla rerum veniam. Repellendus iure ut amet ea temporibus ea et. Ipsa aut autem magni est sit qui excepturi.', 'Eum eos a commodi. Asperiores dolores aliquam excepturi est voluptatem molestias repudiandae. Aut consequatur soluta minus officia ut. Eos dolores molestiae cumque harum. Ipsum pariatur excepturi ducimus vel debitis. Praesentium magni ut fugiat sed quasi. Unde aliquam non aliquid veniam fugiat earum ullam. Praesentium sit sapiente molestiae dicta sequi earum ea quae. Aperiam molestiae quae labore sint non.', '2021-12-20', '2021-12-20', 'SI', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(19, 0, 'Aperiam hic sunt consequuntur iste ea temporibus. Dolores sit voluptatem aliquam nulla rem rem dolorem quis. Dignissimos et et quos aut molestiae assumenda. Qui deserunt ab omnis enim et officiis ut.', 'Odit eveniet quos quaerat eum. Dolor exercitationem harum optio. Itaque suscipit incidunt impedit. Maiores voluptates hic voluptatem. Odio magni consequatur veniam culpa sit debitis. Et beatae non quis quos. In quo esse adipisci aspernatur eligendi. Non quis impedit modi hic enim. Quo non aut itaque sed. Et velit vel ipsam ut libero magni sint.', '2021-12-20', '2021-12-20', 'NO', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(20, 0, 'Nihil dignissimos nulla ut commodi. Rerum omnis deserunt aut est laboriosam. Nihil est animi inventore sequi ut.', 'Enim mollitia sed ullam facilis beatae harum sed qui. Et voluptatibus et mollitia voluptatem deserunt. Tenetur minima cum optio eos. Quaerat sed excepturi quis sapiente. Occaecati earum alias iure non consequatur. Quaerat tempore voluptatem impedit soluta aliquam. Nam ut aut harum est rerum accusamus. Nisi et omnis est enim sapiente saepe odit perspiciatis. Aut et a quis et voluptatem quia.', '2021-12-20', '2021-12-20', 'SI', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(21, 0, 'Et mollitia est repudiandae sunt rerum labore. Quaerat ad id consequatur. Dolores ipsa mollitia mollitia dolor. Earum blanditiis labore est officia.', 'Aut soluta reiciendis quaerat corrupti porro velit qui. Dolores et dolore magni voluptatem eaque nesciunt optio. Placeat minus molestiae et quia vel. Fuga facilis rerum ut eum expedita dolor ullam. Aut dicta recusandae deleniti rem sit quidem tempore. Deserunt quia nesciunt quibusdam mollitia. Vel asperiores architecto qui temporibus voluptatem qui. Odio vitae ut est dolorem.', '2021-12-20', '2021-12-20', 'SI', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(22, 0, 'Quo atque similique eveniet incidunt dolores. Enim nulla pariatur aut dicta. Fugiat labore aut illum maxime optio nihil tenetur.', 'Quam voluptatum dolorem accusantium neque est enim quia dolor. Corrupti similique sequi impedit voluptatibus. Reiciendis dolores quasi quis sed nihil hic. Nam dicta expedita officia labore. Similique eos autem vero in tempora. Ut sequi mollitia ut saepe doloremque cupiditate nihil. Dolore odio inventore omnis quia quod. Maxime itaque natus impedit inventore magni a quibusdam. Quas ut quibusdam dolores omnis aut. Alias inventore voluptatem rem facere omnis totam.', '2021-12-20', '2021-12-20', 'SI', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(23, 0, 'Deleniti id ad recusandae optio cupiditate. Architecto ipsa et et sed. Impedit qui magnam aut libero. Consequatur distinctio voluptatibus dolorum nihil architecto. Et corrupti ea aut modi saepe.', 'Quae quisquam sit perspiciatis sint. Est qui et omnis quia neque aut. Facilis magni rerum blanditiis ut. Dignissimos quas nostrum rerum. Maxime voluptatem itaque eum sunt. Porro est molestiae autem qui. Consequatur eum non repudiandae explicabo fuga ut perferendis quia. Sed voluptatem odio est eos sint. Ea dolorem est est qui harum et. Sint sint et non. Consequatur inventore iusto perspiciatis et maxime. Optio dolores ipsum et dolorem.', '2021-12-20', '2021-12-20', 'NO', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(24, 0, 'Blanditiis expedita quod recusandae. Veritatis pariatur dolorem ut quia ab. Dolor sunt et sunt et nulla dolores quas voluptas.', 'Facere nemo facilis illum iusto sapiente neque dolorem ut. Odio quae ipsa sunt maiores. Accusamus sed adipisci adipisci ullam ipsa neque voluptas. Cumque ipsam inventore tempore numquam. Ipsum enim ullam at id. Rerum numquam laborum ea voluptatem ab laboriosam. Eos hic unde dolores est. Iure dolor autem aut. Ipsam quae sequi quia veritatis laborum. Et sunt illo omnis magnam quis minima.', '2021-12-20', '2021-12-20', 'NO', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(25, 0, 'Rerum autem dolorem hic non quidem sed. Libero voluptate et ipsam et quisquam.', 'Consequuntur rem fugit aliquam consectetur. Veritatis vitae autem est omnis tempora. Nobis quae qui tempora eos sapiente qui. Quisquam magni qui et impedit. Iure eveniet cumque eum officiis consequatur itaque minima. Sapiente nam id et. Sequi est et amet sint consequuntur. Consequuntur quod consequatur adipisci. Modi quia fugit quos doloribus perspiciatis aliquid. Et nobis facilis sunt at est. Voluptas quis pariatur quam tempore nemo.', '2021-12-20', '2021-12-20', 'SI', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(26, 0, 'Officia voluptatem deleniti vitae impedit inventore. Eveniet laboriosam alias itaque pariatur animi rem numquam. Beatae repellat perspiciatis recusandae. Iusto consectetur impedit a quos ut nam ea.', 'Iusto nulla deleniti earum eum. Quis nulla cumque aliquam architecto dolorum perspiciatis. Omnis velit blanditiis sapiente tempora consequatur culpa. Adipisci unde ab eveniet minus. Officia ad asperiores laudantium excepturi. Eveniet facere numquam et ipsa et. Dolorem accusamus quisquam nulla non laboriosam ut. Minus consectetur eum beatae amet modi nobis blanditiis. Et deleniti est nihil iure. Reprehenderit est labore sequi. Qui placeat eos nam placeat corrupti maxime explicabo.', '2021-12-20', '2021-12-20', 'NO', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(27, 0, 'Asperiores tempore eum voluptatem enim molestias nihil dignissimos corporis. Qui aut alias fugit nobis. Omnis rem nulla blanditiis sit laudantium placeat. Et veritatis accusamus et est illo est.', 'Rerum odit assumenda ullam alias aut vitae. Expedita excepturi exercitationem iusto vero. Hic qui quia ad enim iste. Voluptatum ut nostrum dolorem aut porro maiores maxime. In ducimus rerum et eius commodi eaque. Recusandae rerum et corrupti ea cupiditate. Temporibus nihil qui sunt molestiae non quis qui. Vel rerum doloremque sit rem molestiae cupiditate. Assumenda voluptatem quos illum est velit. Enim quod modi quaerat. Odit autem sit blanditiis est quia enim ut.', '2021-12-20', '2021-12-20', 'NO', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(28, 0, 'Consequatur recusandae aut possimus eaque. Ea omnis reiciendis vel ut neque. Ut repellendus rem quis in impedit ab voluptatibus ab. Quia dolorum et perferendis voluptas.', 'Saepe et qui sed nesciunt sapiente ratione. Aperiam autem id quae et tenetur. Eum officiis maxime autem quam placeat. Sequi aut sapiente est. Iusto quaerat rem consectetur. Nam dolores dignissimos nam odit repudiandae. Alias voluptatibus nobis saepe consequuntur. Quo quia cupiditate officia qui et. Tenetur sint consequuntur inventore temporibus impedit placeat dolores. Eos debitis ea ut inventore. Qui neque voluptas vel praesentium quia iusto. Rem repudiandae omnis minima nostrum provident qui.', '2021-12-20', '2021-12-20', 'SI', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(29, 0, 'Qui quo dolor dolorem. Hic aut occaecati animi eum asperiores quia. Eveniet et nihil accusantium ab laudantium iusto. Accusamus qui ut illo labore.', 'Magni aut maiores praesentium et ipsum. Esse odit corporis est recusandae. Dolor qui aut quaerat aut incidunt distinctio. Quis alias occaecati corporis hic doloribus. Quia quos iusto non eveniet voluptate. Ducimus earum et non iure ut. Consequuntur et debitis eveniet nobis molestias corporis voluptas. Quae doloremque tenetur blanditiis reiciendis. Harum minus quo quia qui et ea. Aut fuga reprehenderit modi repellendus voluptas ut. Minima illo dolore magni modi. Fugit quia optio qui itaque.', '2021-12-20', '2021-12-20', 'SI', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(30, 0, 'Officiis corporis ut dicta dolorem. Modi incidunt eos natus tempore. Ullam cupiditate et modi iusto. Error ut in expedita eum earum. Eligendi tenetur praesentium rem. Vel harum ad molestias ut quis.', 'Eaque velit quibusdam excepturi sit qui. Et dignissimos ratione omnis et. Laudantium animi enim natus ratione voluptatibus aut. Et ab optio animi ut adipisci iusto eos. Non repudiandae voluptas placeat quibusdam nam corrupti. Excepturi sunt qui dolore et. Perferendis voluptatibus magni voluptas magni unde expedita. Eligendi tenetur voluptatem est et iusto assumenda. Quas animi earum sit et totam et nesciunt. Rerum sit enim quaerat provident dolore rem.', '2021-12-20', '2021-12-20', 'NO', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(31, 0, 'Accusamus aliquid voluptas aut voluptatem. Omnis doloribus quia eaque. Voluptatem ab alias numquam expedita repellendus corporis perspiciatis eius. Dignissimos deserunt beatae quod iste sit quia.', 'Velit consequatur quos commodi nam incidunt aut debitis. Et quis dolorem sequi molestias accusantium. Repudiandae repellendus voluptatum dolore ducimus. Veniam repellendus consequatur enim labore eos quam ut. Hic quia sed tempore rerum nihil odio. Et quidem quia id enim deleniti. Est et dolorem id quae repellat voluptate.', '2021-12-20', '2021-12-20', 'SI', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(32, 0, 'Ut tempora aut ut. Et voluptas aspernatur aliquam qui nemo. Ea eligendi asperiores amet accusamus. Eum corrupti enim sint magni nihil ut.', 'Ab minus rerum consectetur illum illum. Maxime ipsum voluptate aut aspernatur. Fuga delectus fugiat quae sapiente quidem voluptates velit. Voluptatibus et debitis repellat facere. Facilis a porro vitae modi sed optio iusto. Sint fugiat est corporis beatae minima dolorem. Id impedit occaecati facere. Enim corporis est aspernatur eius ut. Eaque iusto quia beatae assumenda facere voluptate consequuntur. Repudiandae est quas fugiat officia et animi ipsa.', '2021-12-20', '2021-12-20', 'SI', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(33, 0, 'Distinctio et quo et. Minus aspernatur et dolore earum unde ipsa. Dolor dolorem nobis soluta beatae. Provident unde labore quasi dolor.', 'Delectus qui explicabo dolor ut. Iure dolores vel quia. Officia consectetur nemo minima sunt non. Ut tempore et possimus quia eveniet cum quidem id. Numquam ut corporis vel totam. Non doloribus ea ex eaque eius necessitatibus. Aut sed possimus molestiae est quo. Perspiciatis voluptas qui consequatur quaerat. Minus sed tempora facilis nam voluptatem delectus eos. Distinctio consequatur nobis consectetur rerum aut. Ea qui qui officiis qui. Ut laborum non impedit officiis provident sunt.', '2021-12-20', '2021-12-20', 'SI', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(34, 0, 'Possimus natus voluptatum magni aperiam. Unde veniam labore maiores. Iusto non deleniti rerum voluptatum veritatis. Optio soluta maxime voluptate voluptatibus quam possimus aut voluptatibus.', 'Nam deserunt quae nihil unde neque rem rerum. Dolores et voluptates beatae officia distinctio sint reiciendis. Repellendus error quod nam consequatur. Facilis magni aperiam dolore architecto ut. Numquam non aut adipisci aut nostrum nihil provident. Fugiat quam blanditiis atque mollitia amet ea. Ipsam asperiores rerum voluptatem illum autem aut. Ex ut rem enim. Et est laborum voluptatem dolorem consequatur. Voluptatibus est quod ut commodi.', '2021-12-20', '2021-12-20', 'NO', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(35, 0, 'Quia eum distinctio sint quo eaque id culpa. Et dicta minus hic qui culpa.', 'Natus ullam dolores incidunt dolorem. Hic eius velit dolores. Adipisci nemo dolores aut. Consectetur velit aut qui est quod et. Aut nihil id sit ut. Perspiciatis dicta rerum reprehenderit numquam maiores. Quidem facere aut enim. Quis odio enim error aliquid temporibus est. Mollitia id perferendis vel iste nisi. Molestias non nihil ducimus accusamus et.', '2021-12-20', '2021-12-20', 'NO', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(36, 0, 'Aut quod voluptatibus fugit beatae. Voluptatem alias et voluptas sequi. Architecto repellat rem quae mollitia quia. Quia non et aliquid ullam. Eligendi ullam molestiae molestiae sint.', 'Qui nemo dolores et. Neque officia perspiciatis ullam deserunt consequuntur. Rerum voluptas nobis provident quas tempore autem. Natus hic qui exercitationem officia velit ducimus illum eum. Voluptates unde rerum ut sunt vero nisi harum. Velit tempore voluptatum repellendus possimus. Eum commodi deleniti nesciunt commodi. Reprehenderit eum ea voluptatem fugiat minus corrupti sint. Ullam sint maxime similique veniam.', '2021-12-20', '2021-12-20', 'SI', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(37, 0, 'Facilis sed ducimus sed. Accusamus qui nobis neque sunt rerum aperiam qui. Voluptate ea maiores et accusantium aut molestiae aut. Libero odit architecto numquam quis eveniet accusantium.', 'Sed facilis doloremque nobis ducimus voluptatem. Consequatur rerum voluptatem alias non architecto architecto et. Saepe corporis vero ut sit. Laudantium quam vel enim sunt modi ab dolores. Culpa adipisci consequatur praesentium quia commodi. Similique distinctio aut blanditiis et quibusdam molestiae nam. Magnam culpa odio enim accusantium cumque est. Deserunt dicta laborum consequatur odit corporis possimus et nobis.', '2021-12-20', '2021-12-20', 'SI', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(38, 0, 'Reprehenderit ipsa explicabo molestias incidunt. Quod facere et soluta non ex voluptatibus rerum. Sit nihil voluptatem et tempore.', 'Culpa id enim occaecati exercitationem. Est accusantium numquam aspernatur vero. Blanditiis sed animi ut dignissimos omnis. Sint et ipsum tempore. Quaerat odit ullam doloribus architecto unde ut. Eum autem voluptates voluptas rerum explicabo. Blanditiis ea ut quia quod impedit saepe eos quos. Nobis quia nesciunt accusamus quo minima. Excepturi ea similique id ab. Autem sequi quae aut quaerat occaecati. Quis non voluptatem sed libero.', '2021-12-20', '2021-12-20', 'NO', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(40, 0, 'Sunt numquam voluptatibus quo enim. Explicabo accusamus nesciunt temporibus ut explicabo.', 'Cupiditate autem ea et repellendus. Deleniti est iure dolor adipisci accusantium iure. Omnis neque molestiae et nemo. Et asperiores expedita unde voluptates. Recusandae eos consequatur aut minima aut vero. Unde reprehenderit sapiente ipsa perspiciatis et. Ut ipsa omnis placeat eos vel dolore. Suscipit tempore possimus in dolore. Voluptatum error quas illo repudiandae eligendi hic. Id omnis beatae nulla nemo. Dolores neque recusandae nobis.', '2021-12-20', '2021-12-20', 'SI', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(41, 0, 'Vel voluptate reiciendis sint et quisquam. Dolores nesciunt architecto velit. Ut iste deserunt deleniti aut molestiae et praesentium. Dolores perferendis velit est accusantium harum vel consequuntur.', 'Voluptates ut molestiae quis minima quos et id. Vero inventore odit sit quia. Autem assumenda optio dolorem et explicabo odit. Atque qui sint natus fugiat omnis totam nam. Dolores itaque excepturi ut labore. Facere libero quia magnam corrupti ut blanditiis. Dolorem qui culpa totam consequuntur aut veniam. Aut ipsa reiciendis voluptates omnis beatae non.', '2021-12-20', '2021-12-20', 'SI', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(42, 0, 'Tempora voluptas dolore vel facilis occaecati veniam. Et nihil sint rem distinctio provident. Magni voluptatem natus et id molestiae cum.', 'Dolorem molestiae rerum voluptas eum porro. Sit in non autem quas voluptatem. Consectetur aut sit accusantium perspiciatis fuga. Ea delectus in fuga esse alias earum et. Aut sunt consequatur soluta qui et. Iusto et est velit odit sequi cumque. Molestias quisquam labore sit maiores. Distinctio quia inventore voluptatibus reiciendis. Beatae mollitia officia quia perferendis ratione. Quam aut qui ex voluptatem impedit occaecati ipsa. Et sapiente corporis saepe dolorum voluptatum sequi.', '2021-12-20', '2021-12-20', 'NO', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(43, 0, 'Ullam temporibus quam labore hic ut et et. Odit autem quis molestiae. Quasi id voluptas omnis sequi. Quia quaerat soluta et eius.', 'Fugiat accusantium animi odit totam dolorem quae. Et quam optio dolores laudantium. Aut id ratione qui facere. Assumenda hic sapiente vero voluptas id. Accusamus at officia enim qui aut dolores. Architecto sequi est commodi aut sint sit. Consequatur a officia vitae velit voluptatum rem. Quas quia nihil blanditiis reiciendis. Est dolorem maxime animi sapiente. Cum repellat magnam facilis dolor. Nihil sapiente itaque omnis distinctio.', '2021-12-20', '2021-12-20', 'NO', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(44, 0, 'Error beatae ad quisquam fugiat. Repellendus accusamus optio ipsum dicta occaecati non. Ut nihil omnis ab hic voluptas.', 'Vitae nulla assumenda culpa earum qui commodi sint repellat. Soluta quas quae aut beatae natus. Consequatur ipsa consectetur consectetur autem cum. Ullam modi esse qui omnis amet. Vel quia qui quae sint. Rerum illo non aliquid. In perspiciatis aliquam maxime commodi adipisci. Ratione quo qui amet omnis aut ipsa sunt. Non ut repellat officia inventore laudantium expedita dolorem.', '2021-12-20', '2021-12-20', 'SI', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(46, 0, 'Sunt ipsum sunt sunt sunt quis. Tempora rerum deleniti et sit impedit soluta molestias. Earum autem sit adipisci nobis officia. Fuga sint consectetur sint est.', 'Aut delectus quis quasi. Est et ut et recusandae rerum in laborum. Deleniti laudantium iure consectetur accusantium iusto laudantium debitis. Cupiditate perspiciatis deserunt nihil at incidunt aliquam. Eos consequatur illum nobis quam voluptas neque. Qui sed sunt voluptatem non rerum commodi aliquam. Suscipit eligendi repellat quo qui. Deserunt eum at eaque voluptatibus quod.', '2021-12-20', '2021-12-20', 'NO', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(47, 0, 'Quos ut illo qui et alias voluptate cumque. Excepturi animi rerum hic reprehenderit. Sed fugit consequuntur veritatis dolorem cum quibusdam ut. Non aut eaque aliquid ullam veritatis.', 'Odit tempore dignissimos quisquam consequatur iure vel laborum. Ratione et in nihil repellat voluptas quo. Beatae qui iusto dicta et ab ut error. Est incidunt maxime voluptatem repellat esse odio adipisci. Saepe dolores eos autem provident. Reprehenderit voluptate officiis magnam quibusdam. Occaecati voluptatem excepturi iure non ex facere ab sunt. Voluptas aut praesentium minus qui.', '2021-12-20', '2021-12-20', 'SI', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(48, 0, 'Aspernatur rerum ut recusandae. Reiciendis officiis doloremque accusamus quos. Rerum ducimus ex ut fugit iure ex.', 'Sit voluptatem magni animi ratione facere illo voluptas. Qui est qui sit excepturi qui porro sequi. Cupiditate aliquam velit nesciunt quasi. Ullam qui nihil quia delectus. Eveniet veniam in et aliquam occaecati animi consectetur voluptas. Blanditiis tempora nihil unde quisquam sunt id. Quia dolore reprehenderit omnis consequatur officia eos. Doloribus maiores error ea sed. Animi corporis tempore dicta iste. Harum expedita corporis rerum vero ea. Corporis nostrum maiores nam sequi.', '2021-12-20', '2021-12-20', 'SI', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(49, 0, 'Qui voluptatibus velit ad tempore quod tenetur ullam quo. Blanditiis voluptatem ea ipsam consequatur. Et occaecati eveniet magnam possimus magni molestiae.', 'Officia cum id est doloremque aliquam repellat libero. Fuga doloribus recusandae temporibus praesentium. Est aut doloribus quod. Distinctio consequatur velit repellat. Ab eum eligendi repudiandae numquam velit. Error quia dolorem cupiditate velit. Blanditiis ut aut qui exercitationem voluptatem in non. Sit natus quis rerum voluptatibus recusandae. Ab quo autem minima. Molestiae a ducimus velit voluptas repudiandae aliquid. Praesentium perspiciatis neque quo et et.', '2021-12-20', '2021-12-20', 'NO', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(50, 0, 'Praesentium ea sed ullam facere fugit accusantium rerum. Aut consequuntur sed placeat id incidunt. Id dignissimos cum rem doloremque sint.', 'Qui amet quis accusantium ut. Minima veniam cum fugiat ipsum laudantium temporibus. Harum repellendus distinctio blanditiis mollitia. Provident in eius dolores ea voluptatem. At praesentium quaerat reiciendis sunt quaerat. Autem cupiditate est eligendi excepturi rerum. Assumenda deleniti eius aut commodi enim est. Quos atque et quo esse.', '2021-12-20', '2021-12-20', 'SI', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(51, 0, 'Qui quo nostrum natus quia repudiandae velit consequuntur. Non rerum quae nesciunt rerum repellendus. Et explicabo laborum repellendus enim est. Id magnam eum vel non nihil blanditiis totam qui.', 'Illum quam delectus tempore non nostrum ut porro. Harum odit et est nemo id. Voluptatum dolore ut animi id suscipit. Culpa nisi dolor voluptatem est non. Iure suscipit tenetur sed nihil. Sit quod eaque unde occaecati dolorum enim quia. Architecto distinctio libero qui aliquid et. Quia harum aut velit. Rerum velit nulla qui dolore. Atque repellat fugit sunt provident eveniet omnis aut voluptas.', '2021-12-20', '2021-12-20', 'SI', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(52, 0, 'Et nemo voluptatibus aut voluptatem tempora ratione. Hic ut in accusamus qui animi. Iste ea laborum qui tenetur. Et sint enim ad.', 'Rerum voluptas ut quae eum. Assumenda sit rerum repellat sapiente tempore aspernatur. Et vero id ducimus. Nihil explicabo nesciunt iste quia laborum aut. Omnis aut animi ea. Error architecto beatae dolor consequatur et quos. Sit laudantium ea rerum tempore consequatur cupiditate. Architecto quis officiis sunt. Illum assumenda est repellat aliquid et ducimus. Eum hic ratione neque aliquam. Perspiciatis odio eveniet perspiciatis eos quia.', '2021-12-20', '2021-12-20', 'NO', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(53, 0, 'Officiis vel qui natus consequuntur odit. Deleniti facilis vero voluptatem et. A facilis ad quam est est est et dolores. Dolorum sint magnam saepe ratione.', 'Ipsam debitis voluptatibus error quos similique ut. Amet quo similique ut magni est. Voluptatem et eveniet sapiente doloremque est saepe repellendus. Modi vero velit numquam iure molestiae id pariatur. Ut eveniet unde dolor corrupti sapiente. Autem est temporibus et ex eos magnam. Aut odit laboriosam suscipit aut maiores accusamus.', '2021-12-20', '2021-12-20', 'NO', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(54, 0, 'Quia consequuntur doloribus aut et laudantium repellat dolor. Omnis a qui fuga est.', 'Aliquid ipsam sunt laboriosam voluptatem repellat aut voluptatibus odit. Soluta beatae illo laboriosam iure. Aut voluptas expedita quis non. Quos unde pariatur quas rerum quia ea laborum. Consequuntur est aut voluptatem sunt et velit. Optio ut dicta fugiat voluptatem officia quo. Sit quis excepturi cumque ut sit itaque repudiandae. Et delectus expedita doloremque omnis facere laboriosam. Ab omnis quam consequatur. Adipisci dolorum qui ut vel consequatur saepe.', '2021-12-20', '2021-12-20', 'NO', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(55, 0, 'Est quae eligendi dolore fugit eum quos. Dolorum dignissimos est sed eveniet quo. Atque laborum odio et minima ab occaecati accusantium. Incidunt et eligendi ullam nemo iusto.', 'Nulla nihil ad alias consequuntur voluptates ad. Dolor ipsum quia voluptatum et expedita facere id. Voluptate nemo qui eos commodi quos praesentium eveniet. Molestiae molestias id consequuntur. Rerum quis tempore qui qui temporibus at asperiores aliquam. Ad quia sequi earum minima earum illum.', '2021-12-20', '2021-12-20', 'NO', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(56, 0, 'Magnam et odit optio non laborum in voluptas aut. Voluptatem sit nostrum vel exercitationem quo. Ipsam provident distinctio ad voluptatem occaecati. Mollitia quia est dolor eligendi.', 'Modi ut asperiores aliquam eligendi. Accusamus harum est aut voluptate perferendis architecto est. Repellat doloremque ut aspernatur. Nisi architecto occaecati voluptates velit sed omnis commodi. Quos quia voluptas quos vero numquam rerum laboriosam facere. Officiis occaecati minus et amet. Doloremque sit et nesciunt corporis et.', '2021-12-20', '2021-12-20', 'SI', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(58, 0, 'Amet nam delectus voluptas. Cupiditate deleniti sit quia velit assumenda animi ut. Minima adipisci praesentium iste ut.', 'Unde eveniet veniam earum eos voluptatum ad. Est omnis molestias occaecati maxime quidem non. Distinctio consequatur alias accusamus est. Quia quia totam dicta autem. Optio officiis dolor sit placeat nisi numquam. Eveniet sit et et impedit ex ut. Et mollitia amet perferendis molestias illum temporibus ut. Fuga quis iure quia ab amet expedita dolores. Deleniti ea adipisci id id fugiat vero voluptates.', '2021-12-20', '2021-12-20', 'SI', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(59, 0, 'Itaque harum doloribus itaque sit eveniet voluptatum sed temporibus. Magnam pariatur sunt sed in unde. Dolorum alias dolore iure.', 'Ipsa sapiente in dolores qui dolorem. Nisi adipisci in quis quia voluptatem quae veritatis voluptatum. Quo non corporis quo aspernatur ut consequatur laboriosam. Et ratione vero aliquam facilis. Reprehenderit velit quia molestiae possimus sint harum. Ullam sunt consequuntur iure dolorem laudantium. Rerum harum provident quas. Harum quos natus atque omnis. Modi voluptatum eos architecto qui. Doloribus iure et repudiandae et.', '2021-12-20', '2021-12-20', 'SI', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(61, 0, 'Dolor laborum quia vitae explicabo dolorem. Commodi eum omnis dolorem quia. Labore quos ipsa fuga fugiat. Ut aperiam corrupti et placeat.', 'Voluptates ut placeat iusto debitis dolorem est et. Quia error et et commodi iste. Magnam aut dicta voluptatem et culpa nobis earum. Sequi rem alias iure consequatur laudantium veritatis qui exercitationem. Vero aut inventore necessitatibus exercitationem. Officiis rerum porro maiores non distinctio illum esse exercitationem. Incidunt tempore perferendis excepturi qui excepturi nemo dolor.', '2021-12-20', '2021-12-20', 'NO', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(62, 0, 'Est omnis provident aspernatur est. Excepturi magni ut consequatur consequatur qui vel recusandae. Rem ut possimus vel quis.', 'In enim veritatis repudiandae laborum cumque et. Modi voluptatibus sit et tempora unde nemo. Eos aut inventore impedit reprehenderit magnam sequi. Aut ipsam id necessitatibus sint ex debitis eaque. Odit est nihil sit fugiat accusantium earum. Fugit magni aut est voluptatum. Aut modi at reiciendis illo reiciendis repellat. Alias explicabo veniam aut. Eius dolorem ut dolore earum vel eos sint.', '2021-12-20', '2021-12-20', 'SI', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(63, 0, 'Natus in sunt occaecati qui ad ratione. Odit aliquid pariatur porro veritatis quod amet repellat. Deleniti et maiores repellendus maxime aspernatur.', 'Hic id quaerat odio assumenda. Iusto perspiciatis maxime aliquam dolor. Nulla tempore repudiandae et ab minima soluta. Animi laudantium quisquam ut velit et et consequatur. Vel cum cupiditate itaque facilis quia cupiditate placeat ea. Ut et explicabo inventore deserunt architecto sint cupiditate. Natus est dolore cupiditate. Et quis ut ut harum. Laborum cum qui et quia laboriosam.', '2021-12-20', '2021-12-20', 'NO', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(64, 0, 'Ut et dolores voluptas iste quasi. Consequatur itaque omnis iste perspiciatis nisi.', 'Reprehenderit non et odit et quasi praesentium sequi ea. Ut magni eveniet autem saepe excepturi magni. Et in quas doloribus est doloremque unde. Illum at omnis non vel rem. Excepturi illo eum illum maxime autem. Dolorem qui et voluptatum architecto deleniti molestiae. Necessitatibus minima quas doloribus ab voluptas. Soluta rerum qui odit rerum non porro officia aliquid. Tempora vel facere modi provident. Aliquam omnis officia nam sed quis voluptatem.', '2021-12-20', '2021-12-20', 'SI', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(65, 0, 'Non incidunt beatae cumque quo debitis quae consectetur cum. Illo recusandae odit vitae porro nihil. Repellat numquam delectus dolores qui et accusamus. Sequi quis praesentium tempore.', 'Labore velit maiores dolores dicta ex alias. Explicabo illum ut porro quo. Atque esse debitis aut. Voluptas laudantium vitae excepturi eum. Eos dolores adipisci fugiat sint fugiat omnis praesentium. Temporibus aut et hic est sed et. Explicabo vel aut sapiente explicabo qui esse sequi. Est sed veniam eius dicta.', '2021-12-20', '2021-12-20', 'SI', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(66, 0, 'Expedita explicabo autem magni ut consequuntur quis. Autem ipsa commodi enim tenetur quisquam nostrum magnam. Cum et ut omnis hic aut.', 'Tenetur rem dicta sint quia placeat voluptatem. Vel molestiae voluptatibus est consequatur. Consequatur architecto qui saepe numquam consectetur. Aut rem necessitatibus sint eligendi corporis minima iusto. Impedit et tempore sed praesentium. Incidunt dolorem beatae molestias et ex iure aut.', '2021-12-20', '2021-12-20', 'NO', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(67, 0, 'Magnam numquam nesciunt consequatur quaerat sed molestiae et. Ut tempore mollitia quia ex ea est. Consequatur ea nisi autem quo ipsam nihil rerum.', 'Qui quia molestiae provident rem dolores rerum illum. Esse fugit quo neque dolorum tenetur totam ratione. Ipsum aliquid molestiae recusandae labore. Adipisci eos veniam minima omnis necessitatibus maiores et. Dolor neque aut rerum et rerum optio. Facere blanditiis dicta ut ad. Quibusdam non est porro sed velit. Modi vero dolorum aliquam. Inventore tempora quia quia magni aspernatur dolorem officia.', '2021-12-20', '2021-12-20', 'NO', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(68, 0, 'Quam aspernatur qui perferendis nihil cumque odio. Consectetur minus ipsa rerum. Odit qui asperiores corrupti quia doloribus natus.', 'Pariatur repellat et error sed necessitatibus eaque. Repellendus ipsam distinctio nobis ratione. Provident quibusdam omnis cupiditate dolorem repellendus. Voluptatum et ad velit ut. Necessitatibus possimus ea quam voluptatem quaerat repellendus hic accusantium. Corrupti nemo reiciendis omnis et dolor molestias eum autem. Et qui quibusdam sapiente laudantium.', '2021-12-20', '2021-12-20', 'NO', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(69, 0, 'Nulla vero dolorem rerum in consequatur at. Rerum non sit et rerum et doloribus. Illo et eum libero pariatur saepe quas facere. Ea omnis similique provident iure ex.', 'Eum itaque totam aut id hic similique ut. Ut fugit sed perspiciatis at amet. Exercitationem incidunt praesentium officiis quis est nesciunt. Blanditiis et fugiat ut numquam. Aperiam voluptate dolorem harum accusamus. Temporibus labore repellat nihil eos. Qui magni cupiditate est iure sed. Totam quia voluptatem ut ipsam dolor animi ut. Praesentium commodi qui est qui eaque. Aperiam ea quae corporis. Tenetur omnis placeat mollitia quibusdam.', '2021-12-20', '2021-12-20', 'SI', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(70, 0, 'Repudiandae et non est qui nesciunt at explicabo maxime. Iste ipsa libero eum inventore et voluptatibus. Quia nihil ipsum rem dignissimos consectetur odit nemo alias.', 'Sapiente non omnis rerum et corporis. Fugit a unde voluptates dolorem. Ex velit optio ipsam eum molestiae voluptatem repellendus eius. Natus quibusdam consectetur tenetur dolor vel voluptatem impedit. At omnis impedit exercitationem. Earum quasi fugit non rerum. Quos aperiam debitis modi non est ab. Ut quisquam vel tempore autem nihil consequatur ut adipisci.', '2021-12-20', '2021-12-20', 'NO', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(71, 0, 'Exercitationem dolor repudiandae alias sunt aperiam dolores. Officiis ipsa pariatur nam fuga. Tenetur omnis nesciunt rerum.', 'Autem hic quis rerum. Soluta non excepturi ducimus assumenda veritatis facere. Explicabo sit omnis ratione error maxime tempore perferendis. Non necessitatibus necessitatibus ad aut dolorem quae. Eveniet sequi tempore consectetur corporis. Modi voluptates nulla non quasi eligendi. Corrupti blanditiis quisquam autem nam. Molestiae est libero consequuntur quis veritatis. Occaecati nihil ut dolore tenetur. Velit veniam sit veritatis nisi ea.', '2021-12-20', '2021-12-20', 'NO', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(72, 0, 'Et numquam soluta et accusamus odio occaecati modi. Aut minima labore omnis voluptatibus odio sint eos. Vel est earum at et optio. Velit qui blanditiis veniam at harum maiores molestiae.', 'Qui autem maxime iusto qui molestiae quisquam saepe. Atque rerum est vero non quo excepturi. A eaque laboriosam sunt incidunt dolores. Beatae eligendi ipsa quia. Possimus delectus rerum iusto totam fugiat ut qui. Ea id cum odio distinctio tempore velit. Tempora consequatur ut et ut numquam. Facere voluptas consequatur quis mollitia.', '2021-12-20', '2021-12-20', 'SI', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(73, 0, 'Blanditiis ut non et autem esse fugiat sequi. Ad mollitia consequatur ratione nobis. Soluta quasi numquam reiciendis alias enim. Soluta nemo voluptatem ea velit pariatur.', 'Molestiae hic aspernatur quod ipsa sit. Nemo sed assumenda qui sit ut veniam saepe aspernatur. Vitae temporibus et mollitia consectetur aut dolore placeat. Aut illo eos impedit qui. Nam aut aut dignissimos quisquam rerum eum quos. Fugit omnis totam rerum. Eos cupiditate autem sed qui aut ea ullam alias. Harum consequatur porro omnis est deserunt quo. Quam nobis commodi eum nostrum sit.', '2021-12-20', '2021-12-20', 'SI', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(74, 0, 'Pariatur in quis minus vel tenetur beatae ad. Ratione sint qui consequatur nemo. Repellendus voluptatem ut ipsum fuga. Aut illum quidem velit facere. Sunt nisi corporis sit.', 'Tempore magnam nihil commodi aperiam dicta ut. Error et voluptatem quos tempore porro nesciunt qui ipsum. Assumenda aperiam assumenda eveniet distinctio molestias quos qui. Dolores consequuntur explicabo ipsam vel soluta debitis quia. Dolorem repellat numquam sint laboriosam laborum dolorem error. Et eaque alias amet vitae cum quod rem. Tempora voluptates sed error sed ut nihil neque. Omnis nihil et aperiam deleniti officia.', '2021-12-20', '2021-12-20', 'SI', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(75, 0, 'Ea omnis voluptatem vel vero. Est facilis distinctio quia ipsam saepe. Autem veritatis sed et quae.', 'Incidunt enim dolorem et rerum nisi. Delectus esse cumque qui fuga sequi tempore. Voluptatum explicabo ea porro ducimus voluptatem modi inventore. Molestiae natus voluptas perspiciatis maxime. Sequi quaerat doloribus iure harum cumque et vel. Consequatur libero voluptate et nam voluptatum odit ratione rem. Laudantium dolorem natus omnis unde amet illum. Minima qui rerum nesciunt reiciendis eligendi. Et aliquid est alias voluptates.', '2021-12-20', '2021-12-20', 'SI', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(76, 0, 'Similique officiis officia soluta aut voluptas officiis. Adipisci commodi suscipit commodi alias voluptate vel. Libero sed ut voluptatem et est.', 'Deleniti dolorum ut eos consequatur earum praesentium. Laboriosam qui odio minus dignissimos sapiente aut quam et. Architecto natus est commodi neque. Labore beatae nobis sit nulla eveniet. Magnam quis eum enim id. Id possimus quo consectetur perspiciatis. Id rerum nostrum suscipit iure. Aperiam corrupti eius eaque officia impedit qui animi assumenda. Est dolor ducimus ex iusto quam. Omnis qui natus ut quis doloribus repellat.', '2021-12-20', '2021-12-20', 'SI', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(77, 0, 'Consequatur facilis id quod est quo dignissimos sunt. Asperiores molestias odit consequatur omnis ab ex. Sit eveniet illo ut neque.', 'Soluta nulla quo laborum voluptate. Eligendi distinctio id ut vero necessitatibus accusantium asperiores. Provident quod cum omnis et iusto ullam voluptatum. Iusto dolor debitis reprehenderit atque. Ullam distinctio esse veniam perspiciatis illum. Cum facere eveniet occaecati enim a libero et. Vel est excepturi neque consequuntur. Sit sed ad nulla. Suscipit blanditiis incidunt optio dolorem. Quisquam laborum fugit nisi omnis incidunt provident laborum. Laboriosam et amet quae.', '2021-12-20', '2021-12-20', 'SI', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(78, 0, 'Veniam reprehenderit nisi laudantium ut et voluptatibus. Quos quia quia qui impedit soluta reiciendis dolorem soluta. Quo voluptates sed molestiae.', 'Non similique voluptas sapiente qui ipsam et. Sint perferendis perspiciatis nisi ex. Vitae sed officia in. Quasi recusandae harum magni nesciunt. Quo aperiam et minus accusamus numquam et quae. Qui libero dolores ullam ratione rerum. Cum eligendi harum et quidem. Ex eveniet sunt sed quo labore. Ipsum cum eos voluptatem quos sunt occaecati. Occaecati in qui placeat commodi iusto. Sint sed quo repellat delectus placeat perferendis. Maxime in et reprehenderit nihil amet tempora.', '2021-12-20', '2021-12-20', 'SI', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(79, 0, 'Commodi magni perspiciatis est. Dolorem provident voluptate et alias magnam.', 'Omnis unde rerum ad possimus reiciendis doloribus. Dolore et tempora sapiente in hic. Eos in eveniet ex molestiae quo. Excepturi et et architecto dolores nostrum. Cum ut ad mollitia vel consequatur. Quaerat rerum maxime est sed quia. Voluptas enim placeat ut nemo et qui impedit. Ea itaque non est molestias. Et et voluptatem suscipit qui. Velit possimus corrupti aspernatur et dolor autem.', '2021-12-20', '2021-12-20', 'NO', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(80, 0, 'Assumenda id qui et porro. Totam sint quod est dolorem placeat ex. Et ut doloremque nostrum earum velit quod eum.', 'Enim quam at et. Vitae nobis odio qui esse delectus ipsum. Dolorem dolorem corporis et rerum. Ut eligendi est quibusdam ad. Ad fugiat voluptatem quis laboriosam molestias sapiente. Ducimus dolores et a. Quia voluptates non qui. Tempora quo possimus est delectus. Dolores deleniti ut quia consequatur. Est ducimus tempora incidunt autem totam. Ullam odio et est quia molestias velit aspernatur. Rerum ut qui nemo minus dolorem. Aut omnis odit sed ipsam aut cumque.', '2021-12-20', '2021-12-20', 'NO', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(81, 0, 'Repellat sapiente corrupti quia rerum veniam et ullam. Temporibus vitae est eaque qui temporibus. Ut est dolorem quam id nam molestiae. Ex sit in aperiam id aut.', 'Aliquid quisquam repudiandae dolorem eaque. Qui saepe corporis aliquid sequi corporis quo ea. Et qui eum expedita voluptate. Vero dolores sint totam atque. Alias voluptatum sit dignissimos voluptatem ut est. Sunt dignissimos repudiandae tempora quia libero non. Debitis non iste ut adipisci. Eos quod minima commodi perferendis. Dicta dolorem qui ullam cumque. Porro natus cupiditate autem corporis ut. Distinctio autem numquam beatae odio veniam et deleniti.', '2021-12-20', '2021-12-20', 'SI', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(82, 0, 'Ad dolores maiores consequatur et amet cupiditate. Sint dolor ullam et totam esse aperiam aliquid. Aut ab et atque in. Eos quo et illo saepe. Ducimus ea quaerat soluta sit suscipit modi et.', 'Id fugiat vel voluptas molestiae. Fuga vero minus quia consequatur. Laboriosam blanditiis consectetur voluptatem provident et numquam. Necessitatibus sapiente exercitationem unde non voluptas ut. Exercitationem non quidem est numquam totam. Cupiditate quasi odio cum eaque reiciendis itaque dolore. Molestiae distinctio dolorem eum eum eum tenetur velit. Quod corporis sunt nemo earum beatae. Ipsam mollitia est non quo.', '2021-12-20', '2021-12-20', 'SI', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(83, 0, 'Adipisci similique eum nobis totam nulla unde ipsam provident. Aspernatur minus animi beatae ut sit id. Architecto cumque totam rerum magni aspernatur quia. Accusantium est odio odio.', 'Repellendus corrupti maxime debitis esse. Voluptas consequatur dolorum perspiciatis ipsam eum nesciunt. Non consectetur quaerat reiciendis dicta autem sint. Sequi nihil quia unde aspernatur cum saepe. Repellendus minima doloribus reprehenderit sequi quia dolorem eius. Soluta nisi incidunt quia perferendis corporis. Veritatis magni sed nemo velit consectetur. Eaque velit repudiandae tenetur commodi aperiam minus expedita.', '2021-12-20', '2021-12-20', 'NO', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(84, 0, 'Debitis et voluptatum debitis. Optio aut aut fuga sapiente. Omnis laboriosam maxime esse voluptas itaque.', 'Sapiente nihil qui numquam est id magnam. Eum porro autem amet. Qui quaerat vel quo rerum. Voluptatem nihil in eos. Nihil ex est laboriosam sed non tempora quisquam. Iste beatae et est non perspiciatis non eos ducimus. Qui sit nisi maiores dolor facere aut. Aspernatur qui corporis perferendis recusandae non sit. Beatae doloribus error eligendi quaerat cupiditate. Neque amet aut minus blanditiis.', '2021-12-20', '2021-12-20', 'SI', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(85, 0, 'Neque facilis voluptatem repellat atque. Omnis voluptatem laudantium voluptatem vel aut et accusamus quia.', 'Amet non fugiat illum qui quia ullam qui. Praesentium eos illum praesentium. Aperiam dolore sed autem vitae eum. Ipsam dolor ea officia. Mollitia illo consequatur vero praesentium nemo placeat ut. Veritatis voluptas sapiente et eos. Omnis ut aut magni. Nihil error magnam illum. Ipsum qui cupiditate laboriosam consequatur minima blanditiis. Non blanditiis deleniti quia et explicabo sint et sapiente. Ratione suscipit animi aperiam aut odit.', '2021-12-20', '2021-12-20', 'SI', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(86, 0, 'Consectetur quidem veniam libero est minima ut. Nihil aut dolor harum sed. Nobis consequatur eum aut sed modi non non. Tenetur maxime omnis quo occaecati eveniet eveniet.', 'Earum dolore aut molestiae dolore. Sunt at eveniet voluptatum omnis autem. At officia doloribus quidem illum eum. Rerum assumenda odit est ut deleniti incidunt laborum. Et rerum itaque atque ab. At debitis rem labore voluptas omnis voluptatem alias. Laudantium officiis non cupiditate est. Voluptas suscipit et et est. Reiciendis eos nobis odio aut enim eum. Ex ex ut consequatur molestias et est. Saepe rem fugit porro esse cum totam.', '2021-12-20', '2021-12-20', 'NO', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(88, 0, 'Nesciunt repudiandae quia labore in quis occaecati. Ad quisquam beatae ea excepturi. Perferendis vitae assumenda labore sequi recusandae sint.', 'Sint error nemo est omnis earum iusto error. Id aut ad minima qui. Ea maxime vel laborum consequatur similique occaecati. Autem non necessitatibus voluptas consequatur temporibus voluptas voluptatem optio. Autem qui ut vel quod rem delectus quia. Nam cupiditate et officia dignissimos quis sint modi deserunt. Tempore facere quidem voluptatem. Vitae cumque nemo sint vel vel voluptates.', '2021-12-20', '2021-12-20', 'SI', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(89, 0, 'Perferendis qui aliquid pariatur nam alias sint. Voluptatum et exercitationem sunt quo aspernatur. Sint accusantium aspernatur voluptatum est.', 'Illo ea enim rem doloribus tempora quibusdam. Temporibus fugit ipsa repellendus enim incidunt corrupti quia. Quia esse provident et odio odio ratione. Ipsa ullam vitae non maiores maxime. Aut beatae similique consectetur facilis et. Excepturi repellendus saepe omnis maiores officia. Saepe cupiditate velit accusantium explicabo dolore laudantium vel. Repellendus aliquid sint voluptatem quod ipsa. Animi voluptas debitis et sit. Rerum et distinctio qui exercitationem laudantium.', '2021-12-20', '2021-12-20', 'NO', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(90, 0, 'Ullam quas impedit tempore. Voluptate ea inventore doloremque sit esse. Necessitatibus quo maxime rerum ipsum porro. Mollitia non fuga sunt iste est et.', 'Quo ea qui quas veniam. Et quos cupiditate aut debitis excepturi sit autem officiis. Iste dignissimos possimus provident laboriosam. Quaerat et qui ipsam voluptatem. Odit sint blanditiis aperiam ipsa quia illo ab. Eos dicta non omnis dignissimos. Illo officia delectus qui unde itaque. Ea ducimus voluptatem provident. Culpa illum commodi doloribus assumenda quia cupiditate. Sit perferendis quia autem magni. Occaecati et totam quaerat ipsam autem.', '2021-12-20', '2021-12-20', 'NO', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(91, 0, 'Repellendus temporibus quisquam veniam. Aut reiciendis numquam culpa est vel quos qui.', 'Provident eius repellendus doloribus pariatur distinctio aut sunt. Id repellat consequatur alias deleniti. Ipsa illum aspernatur laborum quod quia magnam voluptas. At dolore maiores eaque aut ut ducimus voluptatum. Ullam nisi architecto sint autem necessitatibus fugit similique. Eligendi vitae dolorem voluptas. Omnis unde dignissimos sunt voluptas et sequi. In distinctio sed ab. Rerum quidem accusamus quia est.', '2021-12-20', '2021-12-20', 'NO', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(92, 0, 'Labore repudiandae iste eos et laborum est soluta. Iure praesentium blanditiis illum repellat suscipit praesentium velit molestiae. Quidem voluptas adipisci unde libero et.', 'A ut amet reiciendis mollitia quam soluta. Dolor et consectetur ipsum veniam. Saepe itaque similique natus eligendi porro qui. Consequuntur deserunt officiis illo consequatur omnis consequatur autem reiciendis. Et eius repellendus repellat at. Dolore nobis nihil ab iusto illum. Eos nihil nisi quas. Quibusdam suscipit voluptate autem sit quam veritatis.', '2021-12-20', '2021-12-20', 'NO', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(93, 0, 'Maiores blanditiis accusamus omnis velit ut. Perferendis dolores et perferendis ipsum. Sit iusto tempora qui fuga iste et.', 'Architecto quasi est porro velit rerum. Consequatur expedita ipsum ut et iste dicta hic. Vel quaerat aliquid voluptates. Impedit fugiat assumenda voluptas maxime ut. Culpa voluptates est dolorem quidem. Blanditiis aut atque ut quia. Natus et natus ad ut ipsum ea. Deleniti et similique aut. Adipisci nihil fuga harum et suscipit. Illo et rerum a ipsa praesentium non ut.', '2021-12-20', '2021-12-20', 'SI', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(94, 0, 'Dolores quasi atque assumenda et tempore non. Velit molestiae pariatur error enim. Vitae autem nisi quaerat totam aperiam. Quisquam ipsam suscipit sed autem natus.', 'Et quis vero est cupiditate iure quod. Necessitatibus nesciunt odit ratione dolorem. Error quia modi odio recusandae quis cumque dolores veniam. Magnam et voluptates minus impedit impedit quo id. Eius a ad ut asperiores repudiandae voluptatibus atque. Hic ut ea occaecati fugiat soluta dolore quo. Ipsa deserunt fugiat architecto distinctio quis aliquam odio.', '2021-12-20', '2021-12-20', 'SI', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(95, 0, 'Ea voluptatem rerum eveniet ut molestiae a odio. Sed suscipit et nobis debitis. Dolorem quis quae consequuntur itaque doloremque expedita asperiores.', 'Nobis saepe esse delectus minus dolore quaerat in veniam. Voluptatem sed quia et qui et. Placeat quia enim inventore. Laboriosam officia amet impedit culpa quia dignissimos. Ad omnis delectus est nihil doloribus quisquam adipisci dolorum. Enim et ut similique ullam sunt alias aspernatur. Vel id ducimus itaque fuga iure atque.', '2021-12-20', '2021-12-20', 'SI', '2021-12-20 05:04:04', '2021-12-20 05:04:04'),
	(101, 0, 'dfzzzzzzzzzzzzzz', 'ptz entradazzzzzzzzzzzzz', '2021-12-20', '2021-12-25', 'SI', '2021-12-20 08:13:37', '2022-01-14 03:59:14');
/*!40000 ALTER TABLE `tasks` ENABLE KEYS */;

-- Volcando estructura para tabla tareas.users
CREATE TABLE IF NOT EXISTS `users` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `remember_token` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_unique` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=35 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla tareas.users: ~31 rows (aproximadamente)
/*!40000 ALTER TABLE `users` DISABLE KEYS */;
INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES
	(1, 'David duran', 'davidstevend@hotmail.com', NULL, '$2y$10$2uUAZMCX.sL5ha2VIDk45uc3Ryp0wraENqVCf4.qRqcKlfg10j4Qe', NULL, '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(4, 'Tony Jenkins', 'mcclure.torrey@example.net', '2021-12-20 05:04:03', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'q1Sthl9pk9', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(5, 'Iliana Baumbach', 'zelda01@example.org', '2021-12-20 05:04:03', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'm65kPFBFfY', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(6, 'Kacie Conn', 'lauretta.murazik@example.org', '2021-12-20 05:04:03', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', '7xyRmxphxH', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(7, 'Ashleigh Schoen Jr.', 'mae.beahan@example.org', '2021-12-20 05:04:03', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', '7gQKE337ks', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(8, 'Mrs. Bethany Lind', 'lexi09@example.net', '2021-12-20 05:04:03', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'cdAR9kwGWz', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(9, 'Maegan Tremblay DVM', 'jordon.pfannerstill@example.com', '2021-12-20 05:04:03', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Lren4HlZA5', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(10, 'Susana Ankunding', 'savion11@example.com', '2021-12-20 05:04:03', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'f7GJGMP78j', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(11, 'Jonatan Bernhard', 'elian97@example.com', '2021-12-20 05:04:03', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'e3hg1HVrlL', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(12, 'Oceane Dare', 'elta61@example.org', '2021-12-20 05:04:03', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Pc3Hg2eoID', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(13, 'Dr. Elisha Treutel', 'amy.legros@example.net', '2021-12-20 05:04:03', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'GQaKM6X8aF', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(14, 'Gustave Hills', 'valentin00@example.com', '2021-12-20 05:04:03', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'COur4uRLz4', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(15, 'Dr. Emory Vandervort Sr.', 'claire.feest@example.com', '2021-12-20 05:04:03', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'ymp3syK6W0', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(16, 'Ronaldo Kshlerin PhD', 'alfreda.crooks@example.com', '2021-12-20 05:04:03', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'oHKGXrwlSd', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(17, 'Libby Hyatt', 'violet.boehm@example.com', '2021-12-20 05:04:03', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'R3By0FPBfV', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(18, 'Lolita Auer', 'lrippin@example.org', '2021-12-20 05:04:03', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'EQbHP5OAJr', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(19, 'Juston Gorczany PhD', 'emilie27@example.org', '2021-12-20 05:04:03', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'knh9dgY8Vn', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(20, 'Mr. Regan Boehm MD', 'brandy20@example.net', '2021-12-20 05:04:03', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'gtfTGzsbYb', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(21, 'Emerson Bartoletti Jr.', 'mayert.kraig@example.org', '2021-12-20 05:04:03', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'QSmUdU6vnp', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(22, 'Dr. Darwin Wilkinson IV', 'corrine91@example.com', '2021-12-20 05:04:03', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'HGaFmnH5Wz', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(23, 'Shayne Kuhic II', 'nzemlak@example.net', '2021-12-20 05:04:03', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'ANFZPZQN3O', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(24, 'Donato Blick', 'rosendo.aufderhar@example.com', '2021-12-20 05:04:03', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'IZOGJiekzc', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(25, 'Merlin Fadel PhD', 'carleton16@example.net', '2021-12-20 05:04:03', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'IxDr79IBvU', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(26, 'Ms. Ashlee Cremin', 'irving54@example.com', '2021-12-20 05:04:03', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'qme55aiYCc', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(27, 'Clint Schumm', 'allene.durgan@example.com', '2021-12-20 05:04:03', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'U5oTxxUlZ1', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(28, 'Miss Eunice Pfeffer', 'kohara@example.net', '2021-12-20 05:04:03', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', '2YMjnbNBkB', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(29, 'Madison O\'Hara', 'vkunde@example.net', '2021-12-20 05:04:03', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', '242bRQgzQk', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(30, 'Porter Baumbach Sr.', 'mireya.okuneva@example.com', '2021-12-20 05:04:03', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'pAQaFKKQ6F', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(31, 'Madelyn Dibbert V', 'monahan.lowell@example.net', '2021-12-20 05:04:03', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Ljlb5lUPSk', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(32, 'Dina Roberts', 'yrath@example.net', '2021-12-20 05:04:03', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'wj8uOXDN6C', '2021-12-20 05:04:03', '2021-12-20 05:04:03'),
	(33, 'Fernelly alberto Alvarez cerezo', 'goldeamerica@yahoo.com', NULL, '$2y$10$6pFU.dPrGL.v58KED6DX7e6URL6xyRsKAOFJB7IMkz5xlgPHUhy5S', NULL, '2022-01-14 07:49:55', '2022-01-14 07:49:55');
/*!40000 ALTER TABLE `users` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
